### ISSUE TITLE
Fix strange side-of-paddle behavior

### ISSUE THREAD

**Issue by JeffBuss** [JeffBuss/gametime#48]

**Comment by sljohnson32** [comment]
@JeffBuss Just so you know, the issue here is around how we are measuring collision with the ball and paddle.  I was going to work on the math tomorrow or Tuesday, once other stuff was wrapped up but let me know if you already have thoughts on this.  From what I have gathered, we are going to need to develop a more advanced algorithm to find true collision with the ball.
